import java.io.*;
public class Capital_Cities
{
    public static void main(String[] args)
    {
         System.out.println("These are the List of all the countries. ");
         System.out.println("Type the number beside them to see the caital city.");
         System.out.println("  1) Afganistan");
         System.out.println("  2) Albania");
         System.out.println("  3) Algeria");
         System.out.println("  4) Andorra");
         System.out.println("  5) Angola");
         System.out.println("  6) Antigua and Barbuda");
         System.out.println("  7) Argentina");
         System.out.println("  8) Armenia");
         System.out.println("  9) Australia");
         System.out.println(" 10) Austria");
         System.out.println(" 11) Azerbaijan");
         System.out.println(" 12) Bahamas");
         System.out.println(" 13) Bahrain");
         System.out.println(" 14) Bangladesh");
         System.out.println(" 15) Barbados");
         System.out.println(" 16) Belarus");
         System.out.println(" 17) Belgium");
         System.out.println(" 18) Belize");
         System.out.println(" 19) Benin");
         System.out.println(" 20) Bhutan");
         System.out.println(" 21) Bolivia");
         System.out.println(" 22) Bosnia and Herzegovina");
         System.out.println(" 23) Botswana");
         System.out.println(" 24) Brazil");
         System.out.println(" 25) Brunei");
         System.out.println(" 26) Bulgaria");
         System.out.println(" 27) Burkina Faso");
         System.out.println(" 28) Burundi");
         System.out.println(" 29) Cambodia");
         System.out.println(" 30) Cameroon");
         System.out.println(" 31) Canada");
         System.out.println(" 32) Cape Verde");
         System.out.println(" 33) Central African Republic");
         System.out.println(" 34) Chad");
         System.out.println(" 35) Chile");
         System.out.println(" 36) China");
         System.out.println(" 37) Colombia");
         System.out.println(" 38) Comoros");
         System.out.println(" 39) Congo, Democratic republic");
         System.out.println(" 40) Congo, Republic");
         System.out.println(" 41) Costa Rica");
         System.out.println(" 42) Cote d'Ivoire(Ivory Coast)");
         System.out.println(" 43) Croatia");
         System.out.println(" 44) Cuba");
         System.out.println(" 45) Cyprus");
         System.out.println(" 46) Czech Republic(Czechia)");
         System.out.println(" 47) Denmark");
         System.out.println(" 48) Djibouti");
         System.out.println(" 49) Dominica");
         System.out.println(" 50) Dominican Republic");
         System.out.println(" 51) East Timor");
         System.out.println(" 52) Ecuador");
         System.out.println(" 53) Egypt");
         System.out.println(" 52) El Salvador");
         System.out.println(" 53) England");
         System.out.println(" 54) Equatorial Guinea");
         System.out.println(" 55) Eritrea");
         System.out.println(" 56) Estonia");
         System.out.println(" 57) Eswatini (Swaziland)");
         System.out.println(" 58) Ethiopia");
         System.out.println(" 59) Federated States of Micronesia");
         System.out.println(" 60) Fiji");
         System.out.println(" 61) Finland");
         System.out.println(" 62) France");
         System.out.println(" 63) Gabon");
         System.out.println(" 64) Gambia");
         System.out.println(" 65) Georgia");
         System.out.println(" 66) Germany");
         System.out.println(" 67) Ghana");
         System.out.println(" 68) Greece");
         System.out.println(" 69) Grenada");
         System.out.println(" 70) Guatemala");
         System.out.println(" 71) Guinea");
         System.out.println(" 72) Guinea-Bissau");
         System.out.println(" 73) Guyana");
         System.out.println(" 74) Haiti");
         System.out.println(" 75) Honduras");
         System.out.println(" 76) Hungary");
         System.out.println(" 77) Iceland");
         System.out.println(" 78) India");
         System.out.println(" 79) Indonesia");
         System.out.println(" 80) Iran");
         System.out.println(" 81) Iraq");
         System.out.println(" 82) Ireland");
         System.out.println(" 83) Israel");
         System.out.println(" 84) Italy");
         System.out.println(" 85) Jamaica");
         System.out.println(" 86) Japan");
         System.out.println(" 87) Jordan");
         System.out.println(" 88) Kazakhstan");
         System.out.println(" 89) Kenya");
         System.out.println(" 90) Kiribati");
         System.out.println(" 91) Kosovo");
         System.out.println(" 92) Kuwait");
         System.out.println(" 93) Kyrgyzstan");
         System.out.println(" 94) Laos");
         System.out.println(" 95) Latvia");
         System.out.println(" 96) Lebanon");
         System.out.println(" 97) Lesotho");
         System.out.println(" 98) Liberia");
         System.out.println(" 99) Libya");
         System.out.println("100) Liechtenstein");
         System.out.println("101) Lithuania");
         System.out.println("102) Luxembourg");
         System.out.println("103) Madagascar");
         System.out.println("104) Malawi");
         System.out.println("105) Malaysia");
         System.out.println("106) Maldives");
         System.out.println("107) Mali");
         System.out.println("108) Malta");
         System.out.println("109) Marshall Islands");
         System.out.println("110) Mauritania");
         System.out.println("111) Mauritius");
         System.out.println("112) Mexico");
         System.out.println("113) Moldova");
         System.out.println("114) Monaco");
         System.out.println("115) Mongolia");
         System.out.println("116) Montenegro");
         System.out.println("117) Morocco");
         System.out.println("118) Mozambique");
         System.out.println("119) Myanmar(Burma)");
         System.out.println("103) M");
    }
}
